# Use Docker
runtime: custom
env: flex
# service: default
readiness_check:
  app_start_timeout_sec: 1800
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2

# Use Node without Docker
# runtime: nodejs14
# instance_class: F2