# Use Docker
runtime: custom
env: flex
# service: default
readiness_check:
  app_start_timeout_sec: 1800
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2
manual_scaling:
  instances: 1
# health_check:
#   enable_health_check: False

# Use Node without Docker
# runtime: nodejs14
# instance_class: F2
env_variables:
  API_SERVER_PORT: 8080
  INFURA_PROJECT_ID: 24559873278a4505abdaf7d7d3ea57c7
  REACT_APP_INFURA_PROJECT_ID: 24559873278a4505abdaf7d7d3ea57c7
  REDIS_URL: 10.115.192.27
  REDIS_PORT: 6379

vpc_access_connector:
    name: 'projects/dancingbananas/locations/us-west1/connectors/redis-connector'

#network:
#  NETWORK_NAME: internal
#  SUBNETWORK_NAME: us-west1-internal

network:
  name: us-west1
  subnetwork_name: us-west1-internal