name: GCE deploy

on:
  push:
    branches: [ banana-game ]
  pull_request:
    branches: [ banana-game ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: build 
        run: |
          cd /opt/actions-runner/il-loss-charts
          git pull origin banana-game
          yarn config set workspaces-experimental true
          yarn
          
      - name: restart service
        run: |
          sudo systemctl restart banana-game
